name: fightmatch
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  bottom_picker: ^2.8.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_iconly: ^1.0.2
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter.ttf
    - family: WorkSans
      fonts:
        - asset: assets/fonts/worksans.ttf
    - family: SFPro
      fonts:
        - asset: assets/fonts/sfpro.otf
